# Generated by Django 6.1 on 2026-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('servicio', models.CharField(max_length=100)),
                ('fecha_preferida', models.DateField()),
                ('hora_preferida', models.TimeField()),
                ('mensaje', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'solicitud de cita',
                'verbose_name_plural': 'solicitudes de cita',
                'ordering': ['-creada_en'],
            },
        ),
    ]
